language: node_js
node_js:
- '10'
- '8'
- '6'

cache:
  directories:
  - node_modules

script:
- yarn build
- yarn test
- yarn lint
- yarn test-gen
- yarn test-gen-env
- yarn check

deploy:
  provider: npm
  email: $NPM_AUTH_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    node_js: '8'
  skip_cleanup: true

env:
  global:
  - secure: BYLfuGrikJZU3xtVZQ8/aSt2otDJpnpTtLEVKeKabGIvXcQCjyhOu5xeUFAl2+zaPb72d2oPOgxUJA2F1RGy9s7EKdJ8nS76FgXw7NgHJ3mM/Fb9DpBgZ+SjlPD0N8248PODkFyaolDcmgKkHuZlqXuoXkN6n6eqlzU0XnwpekBdJKHHGx8j95qVrEHrPkVsYo/xjPL4ECK3pwjJWy58MPERrOPuka9lAm1QdMqGsHzXauxxPNqWbeu7vw/7SEnrjN1t0AXYRO5tLD5arjRhHX07lWoxmbA7m7Lk8SL3biIerNpD0d1gGIngF5zXw35y2bISUMBvgWQbTgqPS6z6v0b4ReZf7jNDiGzO7cu1W1eeL37ULhNiO6v3Gn8TwyKuwOSpiYoc6DR/AYQvv09/Ieqf3K3Zq31nkq8h9IHhyrx37JZvfbudpHJRvdOEugWKnUXZnnpjwNL1U/4Dm5HvD8h0wuIPH3+DESntpz2ME+ngwRYeHaahTcoOmbpGd+XTnRlMub8N6ONjLZMGMZlbEy+13KqLrf/1buDEmhX+E8kRaPG0JlsIwHa4/oYRrrfI00mrNJK724rtO5VL9QEFc97YuD1MUt00X3oUHvyALerCLioEFLSeBTIUOW4KhOCEfTrF2AqbyICP6d6irxfhP9EUaX4Z0IRqwP8ByKp2MDc=
  - secure: guu6quOfCnjapELFaPlPwWD59duhd2Hv4ljhNnUYdmA/kthiVMAE3Z/FygABVNyCXc3Nv9j5/mO+85T37oeGn03tvmcaPf41WrrY+bZQUV7dJH8ct1LCaJL9zpC9TmPhGenFmiuzpR51QXkPNicYk14NiorJGxMcMhW1AOEDDHoWPH3UuCytpy3KJ3H0hY69e2I8ByuGlx31hFQ+l7bM81o9e/UJMRFImZ9PeSU5P6Vc89//9k2OfVSUuxCNoI6JpRCadoJuoXedv4jeadrKUML2/ZtXaezTyydHYADw6GyoO9ZsOQUgLbPcACi6r0pmeTihwTWJwWyD48h/geYz0Ijf/he5VanVGf2dlIQZTuqNkPAE+60X9ggCTPyLwNT27gqVl7XVJDmR/VEadVEfeF9yOGs7hcTQTI1raiepW3+1lDQun3s7j1TdK/WSuIkGa/AzoMg34YDZmyIMc2YZGDyle1+0F0IlqssZcQsAh8LVzPmlx6AGBfZ0wzRDMGaLesBhSj0ZcQY8lws0OW70YUFupviW2iqXuBpH/BkOTf3Z7xFTekqh4aXk1t6mGbKkwN31gsp9oNEu05ughGDORJBOGSkGlatLrN2/DBUh8XozLDkXjfpe3Oz0BiyAXbpGJZQpd4h7TxBC9NF+8fSq3xdPj4H07rOhNsDa0aIFQYQ=
